name: ops-home-training
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.10
  - pip:
      - 'azureml-dataset-runtime[pandas,fuse]'
      - azureml-defaults
      - numpy
      - scikit-learn
      - tensorflow
      - opencv-python-headless